#默认配置
server:
  port: 8080
  reactive:
    session:
      timeout: 7200

spring:
  profiles:
    active: dev

  #thymeleaf配置
  thymeleaf:
    cache: false
    mode: 'HTML'
  #邮箱配置
  mail:
    host: smtp.qq.com
    #发送人，需要开启pop3/smtp服务才能发送邮件
    username: '2813958937@qq.com'
    password: 'fylczocjxkhudgii'
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 3MB #设置最大图片不能大于3MB





---
#开发环境
server:
  port: 8081



spring:
  config:
    activate:
      on-profile: dev
# 数据源配置
  datasource:
    druid:
      url: 'jdbc:mysql://localhost:3306/talkber?
      useUnicode = true & characterEncoding = utf8 & useSSL = false & serverTimeZone = UTC &
      allowPublicKeyRetrieval = true & autoReconnect=true'
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123.com
      #配置数据池
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 60000
#      redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 10
        max-wait: 1000
    database: 0



#日志级别
logging:
  level:
    com.talkber: info
    org.springframework: info


---
#生产环境
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: prod